# ! login
POST  http://localhost:3000/api/v1/login 
Content-Type: application/json
 
 {
    "id" : "2ae486de-29fe-4064-8c45-0c5c7fe045c4"
 }

###
# ! register
post  http://localhost:3000/api/v1/register 
Content-Type: application/json

{
   "fullName" : "user",
   "email" : "user1@example.com",
   "password" : "password"
}
